// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251030191120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HostId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 100,
                            DateTime = new DateTime(2025, 11, 29, 19, 11, 19, 312, DateTimeKind.Utc).AddTicks(1897),
                            Description = "Largest tech gathering of the year.",
                            HostId = 1,
                            IsPublic = true,
                            Location = "Kyiv Expo Center",
                            Title = "Annual Tech Conference"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            DateTime = new DateTime(2025, 12, 14, 19, 11, 19, 312, DateTimeKind.Utc).AddTicks(1904),
                            Description = "Hands-on coding session for contributors.",
                            HostId = 1,
                            IsPublic = true,
                            Location = "Online via Zoom",
                            Title = "Open Source Workshop"
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2025, 11, 14, 19, 11, 19, 312, DateTimeKind.Utc).AddTicks(1906),
                            Description = "Discussion on classic literature.",
                            HostId = 2,
                            IsPublic = true,
                            Location = "Central Library",
                            Title = "Local Book Club Meeting"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 10,
                            DateTime = new DateTime(2025, 11, 9, 19, 11, 19, 312, DateTimeKind.Utc).AddTicks(1907),
                            Description = "Team building event (Private).",
                            HostId = 1,
                            IsPublic = false,
                            Location = "Italian Restaurant",
                            Title = "Private Team Dinner"
                        });
                });

            modelBuilder.Entity("Domain.EventParticipant", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("EventParticipants");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            UserId = 1
                        },
                        new
                        {
                            EventId = 1,
                            UserId = 2
                        },
                        new
                        {
                            EventId = 2,
                            UserId = 1
                        },
                        new
                        {
                            EventId = 3,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice.org@event.com",
                            PasswordHash = "$2a$10$wU0T5zJ1z2z3z4z5z6z7z8z9z0z1z2z3z4z5z",
                            Username = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob.user@event.com",
                            PasswordHash = "$2a$10$xU0T5zJ1z2z3z4z5z6z7z8z9z0z1z2z3z4z5z",
                            Username = "Bob"
                        });
                });

            modelBuilder.Entity("Domain.Event", b =>
                {
                    b.HasOne("Domain.User", "Host")
                        .WithMany("HostedEvents")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Domain.EventParticipant", b =>
                {
                    b.HasOne("Domain.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Event", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Navigation("HostedEvents");

                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
